import { z } from "zod";
import { createAgent } from "@slad/pipeline";
import { definePipeline, defineStage } from "@slad/pipeline";
import type { ModelProvider } from "@slad/model-providers";

/**
 * {{Name}} agent — generated by `slad create agent {{name}}`.
 *
 * Built only on the public SLAD SDK: defineStage → definePipeline → createAgent.
 * Swap `mockProvider` for `getProvider("cli")`
 * to run against a real model.
 */

const greetStage = defineStage<{ topic: string }, { message: string }>({
  id: "{{id}}.greet",
  inputSchema: z.object({ topic: z.string() }),
  outputSchema: z.object({ message: z.string() }),
  async run(input, ctx) {
    const message = await ctx.model.generateText({
      system: "You are {{name}}. Respond in one short sentence.",
      input: { topic: input.topic },
    });
    return { message };
  },
});

const pipeline = definePipeline({
  id: "{{id}}",
  version: "0.1.0",
  stages: [greetStage],
});

const mockProvider: ModelProvider = {
  name: "cli",
  async complete() {
    return "Hello from {{name}}.";
  },
};

export const {{name}}Agent = createAgent<{ topic: string }, { message: string }>({
  id: "{{id}}",
  model: mockProvider,
  pipeline,
});

// Run directly: `pnpm start`
const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const result = await {{name}}Agent.run({ topic: "hello world" });
  console.log(result.output?.message ?? "(no output)");
}
