import { z } from "zod";
import { createAgent } from "@slad/agent";
import { definePipeline, defineStage } from "@slad/pipeline";
import type { ModelProvider } from "@slad/model-providers";

/**
 * Demo agent — generated by `slad create agent demo`.
 *
 * Built only on the public SLAD SDK: defineStage → definePipeline → createAgent.
 * Swap `mockProvider` for `getProvider("anthropic", process.env.ANTHROPIC_API_KEY)`
 * to run against a real model.
 */

const greetStage = defineStage<{ topic: string }, { message: string }>({
  id: "demo.greet",
  inputSchema: z.object({ topic: z.string() }),
  outputSchema: z.object({ message: z.string() }),
  async run(input, ctx) {
    const message = await ctx.model.generateText({
      system: "You are demo. Respond in one short sentence.",
      input: { topic: input.topic },
    });
    return { message };
  },
});

const pipeline = definePipeline({
  id: "demo",
  version: "0.1.0",
  stages: [greetStage],
});

const mockProvider: ModelProvider = {
  name: "anthropic",
  async complete() {
    return "Hello from demo.";
  },
};

export const demoAgent = createAgent<{ topic: string }, { message: string }>({
  id: "demo",
  model: mockProvider,
  pipeline,
});

// Run directly: `pnpm start`
const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const result = await demoAgent.run({ topic: "hello world" });
  console.log(result.output?.message ?? "(no output)");
}
