import { z } from "zod";
import { defineStage } from "@slad/pipeline";

const {{Name}}Input = z.object({
  prompt: z.string().min(1),
});

const {{Name}}Output = z.object({
  text: z.string(),
});

/**
 * {{Name}} — generated by `slad create stage {{name}}`.
 *
 * An LLM stage: validates its input, calls the model adapter exposed on the
 * stage context, and returns a validated output.
 */
export const {{name}}Stage = defineStage<
  z.infer<typeof {{Name}}Input>,
  z.infer<typeof {{Name}}Output>
>({
  id: "{{id}}",
  description: "TODO: describe what the {{name}} stage produces.",
  inputSchema: {{Name}}Input,
  outputSchema: {{Name}}Output,
  permissions: ["network"],
  async run(input, ctx) {
    const text = await ctx.model.generateText({
      system: "TODO: system prompt for {{name}}.",
      input: { prompt: input.prompt },
    });
    return { text };
  },
});
