import { z } from "zod";
import { defineStage, definePipeline } from "@slad/pipeline";

/**
 * {{Name}} — generated by `slad create pipeline {{name}}`.
 *
 * A sequential pipeline: each stage's validated output feeds the next stage's
 * input. Replace these placeholder stages with your own (or import them).
 */

const firstStage = defineStage<{ input: string }, { draft: string }>({
  id: "{{id}}.first",
  inputSchema: z.object({ input: z.string() }),
  outputSchema: z.object({ draft: z.string() }),
  async run(input) {
    return { draft: `draft: ${input.input}` };
  },
});

const secondStage = defineStage<{ draft: string }, { final: string }>({
  id: "{{id}}.second",
  inputSchema: z.object({ draft: z.string() }),
  outputSchema: z.object({ final: z.string() }),
  async run(input) {
    return { final: input.draft.toUpperCase() };
  },
});

export const {{name}}Pipeline = definePipeline({
  id: "{{id}}",
  version: "0.1.0",
  stages: [firstStage, secondStage],
});
