import { z } from "zod";
import { defineTool } from "@slad/tools";

/**
 * {{Name}} — generated by `slad create tool {{name}}`.
 *
 * A typed, validated, permission-aware tool. Replace the body of `run` with the
 * real side effect (HTTP call, shell exec, MCP request, …).
 */
export const {{name}}Tool = defineTool({
  id: "{{id}}",
  description: "TODO: describe what {{name}} does.",
  permissions: ["network:read"],
  input: z.object({
    query: z.string().min(1),
  }),
  output: z.object({
    result: z.string(),
  }),
  risk: "low",
  async run(_ctx, input) {
    // TODO: implement the real effect.
    return { result: `{{name}} received: ${input.query}` };
  },
});
