/**
 * slad.config.ts — configuration for the "{{name}}" agent project.
 * Generated by `slad create agent {{name}}`.
 */
export default {
  id: "{{id}}",
  /** Default model provider. Set the matching API key in your environment. */
  provider: "anthropic",
  /** Where this project keeps its agents, tools, and (optionally) pipelines. */
  paths: {
    agents: "./agents",
    tools: "./tools",
  },
} as const;
