/**
 * slad.config.ts — enterprise configuration for "{{name}}".
 * Generated by `slad create agent {{name}} --template enterprise`.
 */
export default {
  id: "{{id}}",
  provider: "anthropic",
  paths: {
    agents: "./agents",
    tools: "./tools",
    stages: "./stages",
    pipelines: "./pipelines",
    prompts: "./prompts",
    policies: "./policies",
    memory: "./memory",
  },
  safety: {
    /** Opt-in harness. "off" | "strict" | "full". */
    mode: "strict",
    maxPermission: "workspace",
  },
  observability: {
    telemetry: true,
    audit: true,
  },
} as const;
